apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnv-gitops-vms
  namespace: openshift-gitops
spec:
  destination:
    namespace: beehive-virtual-machines
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/dev  # Change to 'overlays/prod' for production
    repoURL: https://github.com/ravishar-rh/gitops-vms
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
